### ISSUE TITLE
add support of command line

### ISSUE THREAD

**Issue by CunliangGeng** [sdrogers/nplinker#219]
Besides using nplinker in [python environment](https://nplinker.github.io/nplinker/latest/quickstart/#4-run-nplinker), users may also like using command lines for nplinker. This feature request is originally from Artem. 

Some example commands users might desire:
```
npl --help

npl load all                          # load all data

npl get bgcs                          # get all bgc data (in csv format?)
npl get bgcs --count                  # get the number of bgcs

npl get links                         # get all links (in csv format?)
npl get links --filter "some-filter"  # get filtered links (what format of filter to use?)
```

Questions
- [ ] what requirements users might have on command lines
- [ ] for what tasks users prefer using command line

## Tasks
- [ ] send the questions to the community

**Comment by justinjjvanderhooft** [comment]
Great suggestion Cunliang - perhaps good to ask in the Slack channel as well? And discuss in the next community call? I would see opportunities for large(r) scale computation of scores, and the streamlined/validated loading of paired data.

**Comment by CunliangGeng** [comment]
@justinjjvanderhooft Artem asked for this feature and will add some requirements to this issue.

**Comment by artfet** [comment]
I was thinking that it would be great if you could run NPLinker directly from the command line with some simple standard inputs, such as what the input data is and where to write the results data (all running with standard parameters in this case). Currently it seems a bit confusing as to how NPLinker should be run to me. I am sorry if my description is a bit too vague, but feel free to ask if what I said was confusing.
